example1:	example1.o 
	g++ -o example1 example1.o
example1.o:	example1.cpp 
	g++ -c example1.cpp
#This is a comment 
#.PHONY 
# @ at the start means do not echo the command in the terminal
run: 
	@./example1