syntax_error:	syntax_error.o
	g++ -o syntax_error syntax_error.o
syntax_error.o:	syntax_error.cpp
	g++ -c syntax_error.cpp

#This is a comment 
#.PHONY 
# @ at the start means do not echo the command in the terminal
run: 
	@./syntax_error